"use client";

import { Amplify } from "aws-amplify";
import outputs from "@/amplify_outputs.json";

/**
 * Configures Amplify on the client for the whole app. Mounted once in the root
 * layout. `ssr: true` lets Amplify share auth state between server and client in
 * the App Router. Renders nothing.
 *
 * `amplify_outputs.json` is generated by `ampx sandbox` / pipeline deploy and is
 * git-ignored — run a sandbox before `npm run dev` or this import will fail.
 */
Amplify.configure(outputs, { ssr: true });

export default function ConfigureAmplify() {
  return null;
}
